targets:
  $default:
    builders:
      json_serializable_optional:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/**
            - test/**
            - example/**
      json_serializable:json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
          exclude:
            - test/**
            - lib/**
            - example/**


builders:
  json_serializable_optional:
    import: "package:json_serializable_optional/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": ["json_serializable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
